version: "3"
services:
  app:
    container_name: container2
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  container1:
    container_name: mongo
    image: mongo
    ports:
      -'27017:27017'
