version: "3"
services:
  app:
    container_name: nodejs-app
    restart: always
    build: .
    ports: 
      -'80:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      -'27017:27017'
